/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    suites: Suite;
    amenities: Amenity;
    differentials: Differential;
    offers: Offer;
    popups: Popup;
    testimonials: Testimonial;
    faqs: Faq;
    attractions: Attraction;
    'photo-categories': PhotoCategory;
    posts: Post;
    'post-categories': PostCategory;
    'design-system': DesignSystem;
    media: Media;
    users: User;
    forms: Form;
    'form-submissions': FormSubmission;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    suites: SuitesSelect<false> | SuitesSelect<true>;
    amenities: AmenitiesSelect<false> | AmenitiesSelect<true>;
    differentials: DifferentialsSelect<false> | DifferentialsSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    popups: PopupsSelect<false> | PopupsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    attractions: AttractionsSelect<false> | AttractionsSelect<true>;
    'photo-categories': PhotoCategoriesSelect<false> | PhotoCategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'post-categories': PostCategoriesSelect<false> | PostCategoriesSelect<true>;
    'design-system': DesignSystemSelect<false> | DesignSystemSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('pt-BR' | 'en') | ('pt-BR' | 'en')[];
  globals: {
    header: Header;
    footer: Footer;
    'booking-bar': BookingBar;
    'newsletter-section': NewsletterSection;
    'testimonials-section': TestimonialsSection;
    'floating-actions': FloatingAction;
    'promotion-page': PromotionPage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'booking-bar': BookingBarSelect<false> | BookingBarSelect<true>;
    'newsletter-section': NewsletterSectionSelect<false> | NewsletterSectionSelect<true>;
    'testimonials-section': TestimonialsSectionSelect<false> | TestimonialsSectionSelect<true>;
    'floating-actions': FloatingActionsSelect<false> | FloatingActionsSelect<true>;
    'promotion-page': PromotionPageSelect<false> | PromotionPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'pt-BR' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Gerado a partir do título. Se já existir outro igual, ganha um sufixo numérico.
   */
  slug?: string | null;
  /**
   * Arraste para reordenar. Cada bloco é uma seção da página.
   */
  layout?:
    | (
        | {
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            image: number | Media;
            /**
             * Vazio usa o título da página.
             */
            title?: string | null;
            variant?: ('page' | 'article') | null;
            /**
             * A assinatura do hotel ("o melhor preço garantido") vem das configurações. Desmarque em páginas onde ela não faz sentido, como a de vagas.
             */
            showTagline?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageHero';
          }
        | {
            image: number | Media;
            eyebrow?: string | null;
            title: string;
            text?: string | null;
            ctaLabel?: string | null;
            ctaUsesEngine?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about';
          }
        | {
            images?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            eyebrow?: string | null;
            title: string;
            /**
             * Linha em branco separa parágrafos.
             */
            text?: string | null;
            ctaLabel?: string | null;
            ctaUsesEngine?: boolean | null;
            reverse?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutMosaic';
          }
        | {
            image: number | Media;
            eyebrow?: string | null;
            title: string;
            text?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            align?: ('right' | 'left') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'regionCard';
          }
        | {
            title?: string | null;
            /**
             * Vazio usa o Instagram cadastrado em Configurações.
             */
            handle?: string | null;
            images?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'instagramStrip';
          }
        | {
            eyebrow?: string | null;
            /**
             * A última palavra sai em vermelho.
             */
            title: string;
            text?: string | null;
            /**
             * Linha com barra vermelha. Ex.: horário do café.
             */
            note?: string | null;
            /**
             * Puxa da collection Comodidades.
             */
            amenitiesScope?: ('none' | 'hotel' | 'quarto') | null;
            /**
             * 1 imagem = coluna. 2 = par lado a lado.
             */
            images?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            reverse?: boolean | null;
            background?: ('white' | 'gray' | 'brand') | null;
            ctaLabel?: string | null;
            gallery?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitContent';
          }
        | {
            title?: string | null;
            cardsLimit?: number | null;
            perksLimit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'differentials';
          }
        | {
            /**
             * Linha pequena acima do título. Vazio esconde.
             */
            eyebrow?: string | null;
            title?: string | null;
            text?: string | null;
            linkLabel?: string | null;
            linkHref?: string | null;
            /**
             * O site atual não exibe preços.
             */
            showPrice?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'suitesCarousel';
          }
        | {
            intro?: {
              title?: string | null;
              text?: string | null;
              ctaLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'roomList';
          }
        | {
            title?: string | null;
            ghost?: string | null;
            text?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cityBand';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            text?: string | null;
            limit?: number | null;
            linkLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'offers';
          }
        | {
            lead?: string | null;
            title?: string | null;
            images?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'social';
          }
        | {
            title?: string | null;
            category?: ('todas' | 'geral' | 'cafe' | 'quartos' | 'localizacao' | 'politicas') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            title?: string | null;
            showFilters?: boolean | null;
            allLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            text?: string | null;
            poiTitle?: string | null;
            poiLimit?: number | null;
            showContactCards?: boolean | null;
            showMap?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'location';
          }
        | {
            title?: string | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'postList';
          }
        | {
            title: string;
            text?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            onlyWhenEmpty?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'emptyState';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            text?: string | null;
            /**
             * Criado em Formulários.
             */
            form?: (number | null) | Form;
            /**
             * Vazio, usa o aceite padrão de contato. Numa página de vagas o aceite é outro — os dados servem para avaliar a candidatura, não para receber conteúdo.
             */
            consentText?: string | null;
            /**
             * Vazio, o card não aparece e o formulário ocupa a largura toda — para páginas onde a central de reservas não faz sentido.
             */
            asideTitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
        | {
            icon?: ('i-mail' | 'i-phone' | 'i-wa' | 'i-cal' | 'i-star') | null;
            title: string;
            text?: string | null;
            /**
             * Sempre abre o motor de reservas — é o único caminho que faz sentido depois da conversão.
             */
            ctaLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'confirmation';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            background?: ('white' | 'gray' | 'brand') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
      )[]
    | null;
  showBookingBar?: boolean | null;
  showTestimonials?: boolean | null;
  /**
   * Vazio = no fim da página, depois de todos os blocos. Informe o número do bloco (1 = primeiro) para inserir a seção logo depois dele — a home do cliente coloca os depoimentos antes das dúvidas frequentes.
   */
  testimonialsAfterBlock?: number | null;
  showNewsletter?: boolean | null;
  newsletterVariant?: ('home' | 'inner') | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descreve a imagem para leitores de tela e para quando ela não carrega.
   */
  alt: string;
  /**
   * Define em qual filtro a foto aparece na página Fotos.
   */
  category?: (number | null) | PhotoCategory;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-categories".
 */
export interface PhotoCategory {
  id: number;
  title: string;
  order?: number | null;
  /**
   * Gerado a partir do título. Se já existir outro igual, ganha um sufixo numérico.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Conecta este formulário ao CRM. A submissão sempre fica salva no Payload; o envio ao GHL acontece depois e nunca quebra o envio do site.
   */
  ghl?: {
    enabled?: boolean | null;
    /**
     * Deixe em branco para usar a subconta padrão definida em GHL_LOCATION_ID.
     */
    locationId?: string | null;
    /**
     * Aparece no contato do GHL e permite filtrar os leads vindos do site.
     */
    source?: string | null;
    /**
     * Use para separar newsletter, contato e pop-up dentro do GHL.
     */
    tags?:
      | {
          tag: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Só preencha para corrigir um campo que o reconhecimento automático errou. Campos sem destino equivalente no GHL (mensagem, observações) viram uma nota no contato.
     */
    fieldMap?:
      | {
          /**
           * Exatamente o "Name" do campo na aba Fields.
           */
          formField: string;
          target:
            | 'firstName'
            | 'lastName'
            | 'name'
            | 'email'
            | 'phone'
            | 'companyName'
            | 'address1'
            | 'city'
            | 'state'
            | 'postalCode'
            | 'website'
            | 'custom'
            | 'ignore';
          /**
           * A key exata do custom field na subconta do GHL.
           */
          customKey?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Tipos de quarto. A ordem controla a sequência na home e na listagem.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suites".
 */
export interface Suite {
  id: number;
  title: string;
  /**
   * Gerado a partir do título. Se já existir outro igual, ganha um sufixo numérico.
   */
  slug?: string | null;
  /**
   * Aparece no card da home. Ex.: "Casal". Vazio usa o nome completo.
   */
  shortName?: string | null;
  order?: number | null;
  /**
   * Uma linha, usada no card do carrossel da home.
   */
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Viram o carrossel do card na página de Acomodações. As setas e os pontinhos são gerados pela quantidade.
   */
  photos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Aparecem com ícone no card. A ordem escolhida aqui é a ordem exibida.
   */
  amenities?: (number | Amenity)[] | null;
  maxGuests?: number | null;
  /**
   * Opcional. Permite linkar direto para o quarto no Omnibees.
   */
  engineCode?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Itens reutilizados pelas acomodações e pela página do hotel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities".
 */
export interface Amenity {
  id: number;
  title: string;
  /**
   * Do sprite do site.
   */
  icon?:
    | (
        | 'i-coffee'
        | 'i-wifi'
        | 'i-parking'
        | 'i-paw'
        | 'i-card'
        | 'i-wa'
        | 'i-bed'
        | 'i-ac'
        | 'i-tv'
        | 'i-desk'
        | 'i-dryer'
        | 'i-bath'
        | 'i-minibar'
        | 'i-phone'
        | 'i-mail'
        | 'i-pin'
        | 'i-star'
        | 'i-tag'
        | 'i-promo'
        | 'i-cal'
        | 'i-pool'
        | 'i-ev'
        | 'i-clean'
        | 'i-fan'
        | 'i-ig'
        | 'i-fb'
      )
    | null;
  scope?: ('quarto' | 'hotel') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Vantagens do hotel. "Destaque" vira card com foto; "Apoio de venda" vira caixa com ícone.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "differentials".
 */
export interface Differential {
  id: number;
  title: string;
  kind: 'destaque' | 'venda';
  order?: number | null;
  /**
   * Usada no card grande.
   */
  image?: (number | null) | Media;
  /**
   * Do sprite do site.
   */
  icon?:
    | (
        | 'i-coffee'
        | 'i-wifi'
        | 'i-parking'
        | 'i-paw'
        | 'i-card'
        | 'i-wa'
        | 'i-bed'
        | 'i-ac'
        | 'i-tv'
        | 'i-desk'
        | 'i-dryer'
        | 'i-bath'
        | 'i-minibar'
        | 'i-phone'
        | 'i-mail'
        | 'i-pin'
        | 'i-star'
        | 'i-tag'
        | 'i-promo'
        | 'i-cal'
        | 'i-pool'
        | 'i-ev'
        | 'i-clean'
        | 'i-fan'
        | 'i-ig'
        | 'i-fb'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Fora da janela de vigência a promoção deixa de aparecer no site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  title: string;
  /**
   * Gerado a partir do título. Se já existir outro igual, ganha um sufixo numérico.
   */
  slug?: string | null;
  /**
   * Texto curto do card.
   */
  summary?: string | null;
  image: number | Media;
  /**
   * Até 4 imagens. Com 4 fotos, a página usa o mosaico 2×2 do modelo.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  highlight?: string | null;
  minimumNights?: number | null;
  suites?: (number | Suite)[] | null;
  /**
   * Vazio = já vale.
   */
  startsAt?: string | null;
  /**
   * Passada a data, some do site sozinho. Vazio = sem prazo.
   */
  endsAt?: string | null;
  conditions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  validityRules?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  whatsappLabel?: string | null;
  emailLabel?: string | null;
  engineLabel?: string | null;
  /**
   * Vazio: o site escolhe automaticamente até 3 promoções vigentes.
   */
  relatedOffers?: (number | Offer)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Aparecem sobre o site conforme o gatilho. Fora da vigência somem sozinhos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popups".
 */
export interface Popup {
  id: number;
  /**
   * Só para você identificar na lista. Não aparece no site.
   */
  title: string;
  isActive?: boolean | null;
  /**
   * Define como o pop-up se monta. O visual segue o design system.
   */
  variant: 'text' | 'image' | 'form';
  eyebrow?: string | null;
  /**
   * A última palavra sai em vermelho, como no resto do site.
   */
  heading: string;
  text?: string | null;
  image?: (number | null) | Media;
  /**
   * No celular a imagem sempre vai para cima.
   */
  imagePosition?: ('side' | 'top') | null;
  /**
   * Criado em Formulários. O redirect de sucesso dele vale aqui também.
   */
  form?: (number | null) | Form;
  consentText?: string | null;
  ctaLabel?: string | null;
  ctaType?: ('engine' | 'engineDates' | 'link' | 'close') | null;
  ctaHref?: string | null;
  /**
   * O motor abre já com esta data preenchida.
   */
  ctaCheckIn?: string | null;
  /**
   * Datas no passado levam a uma busca vazia — alinhe com a expiração do pop-up.
   */
  ctaCheckOut?: string | null;
  trigger: 'delay' | 'scroll' | 'exit' | 'immediate';
  delaySeconds?: number | null;
  scrollPercent?: number | null;
  frequency: 'session' | 'days' | 'always';
  frequencyDays?: number | null;
  /**
   * Quem enviou o formulário ou clicou no botão não vê o pop-up de novo.
   */
  hideAfterConvert?: boolean | null;
  /**
   * Vazio = já vale.
   */
  startsAt?: string | null;
  /**
   * Passada a data, some do site sozinho.
   */
  endsAt?: string | null;
  showOn: 'all' | 'only' | 'except';
  pages?: (number | Page)[] | null;
  position?: ('center' | 'corner') | null;
  size?: ('sm' | 'md' | 'lg') | null;
  theme?: ('light' | 'dark') | null;
  /**
   * Só um pop-up aparece por página. Havendo mais de um elegível, ganha o de maior prioridade.
   */
  priority?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  title: string;
  /**
   * Sem aspas — o layout já as coloca.
   */
  quote: string;
  author: string;
  source?: ('tripadvisor' | 'google' | 'booking' | 'direto') | null;
  /**
   * Quantidade de estrelas exibidas.
   */
  rating: number;
  url?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('geral' | 'cafe' | 'quartos' | 'localizacao' | 'politicas') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Alimentam a lista da página Localização.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attractions".
 */
export interface Attraction {
  id: number;
  title: string;
  /**
   * Exibido como "450 metros" ou "1,7 km" conforme o valor.
   */
  distanceMeters: number;
  kind?: ('geral' | 'compras' | 'cultura' | 'eventos' | 'transporte') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Gerado a partir do título. Se já existir outro igual, ganha um sufixo numérico.
   */
  slug?: string | null;
  publishedAt?: string | null;
  category?: (number | null) | PostCategory;
  /**
   * Destacada com a barra vermelha no topo do artigo. Opcional.
   */
  lead?: string | null;
  /**
   * Usado no card da listagem e nos relacionados.
   */
  excerpt: string;
  image: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedSuites?: (number | Suite)[] | null;
  relatedAttractions?: (number | Attraction)[] | null;
  /**
   * Vazio: o site mostra os artigos mais recentes automaticamente.
   */
  relatedPosts?: (number | Post)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories".
 */
export interface PostCategory {
  id: number;
  title: string;
  /**
   * Gerado a partir do título. Se já existir outro igual, ganha um sufixo numérico.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cores, tipografia, espaçamento e formas. Só um documento fica ativo por vez.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-system".
 */
export interface DesignSystem {
  id: number;
  name: string;
  isActive?: boolean | null;
  colors: {
    /**
     * --red
     */
    brand: string;
    /**
     * --red-dark
     */
    brandDark: string;
    /**
     * --ink
     */
    ink: string;
    /**
     * --gray-text
     */
    inkSoft: string;
    /**
     * --gray-soft
     */
    inkMute: string;
    /**
     * --gray-bg
     */
    surface: string;
    /**
     * --gray-line
     */
    line: string;
    /**
     * --ink-2
     */
    footer: string;
    /**
     * --ink-3
     */
    dark: string;
    /**
     * --pink
     */
    accent: string;
    /**
     * --wa
     */
    whatsapp: string;
  };
  typography: {
    /**
     * --ff-head
     */
    displayFamily: string;
    /**
     * --ff-body
     */
    bodyFamily: string;
    /**
     * Carregada no <head>. Deixe vazio se as fontes forem auto-hospedadas.
     */
    webfontUrl?: string | null;
    baseSize: number;
    baseLineHeight: number;
    headingSize: number;
  };
  layout: {
    /**
     * --shell
     */
    container: number;
    sectionSpacing: number;
    heroHeight: number;
    pageHeroHeight: number;
  };
  shape: {
    buttonRadius: number;
    cardRadius: number;
    /**
     * Valor CSS de box-shadow. "none" para desligar.
     */
    cardShadow?: string | null;
  };
  promotion: {
    galleryHeight: number;
    galleryGap: number;
    contentGap: number;
    relatedColumns: number;
    detailMaxWidth: number;
  };
  customCss?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Só administradores criam usuários e alteram perfis.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  ghlStatus?: ('sent' | 'failed' | 'skipped') | null;
  ghlContactId?: string | null;
  ghlError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'suites';
        value: number | Suite;
      } | null)
    | ({
        relationTo: 'amenities';
        value: number | Amenity;
      } | null)
    | ({
        relationTo: 'differentials';
        value: number | Differential;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'popups';
        value: number | Popup;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'attractions';
        value: number | Attraction;
      } | null)
    | ({
        relationTo: 'photo-categories';
        value: number | PhotoCategory;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'post-categories';
        value: number | PostCategory;
      } | null)
    | ({
        relationTo: 'design-system';
        value: number | DesignSystem;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              image?: T;
              id?: T;
              blockName?: T;
            };
        pageHero?:
          | T
          | {
              image?: T;
              title?: T;
              variant?: T;
              showTagline?: T;
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              image?: T;
              eyebrow?: T;
              title?: T;
              text?: T;
              ctaLabel?: T;
              ctaUsesEngine?: T;
              id?: T;
              blockName?: T;
            };
        aboutMosaic?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              eyebrow?: T;
              title?: T;
              text?: T;
              ctaLabel?: T;
              ctaUsesEngine?: T;
              reverse?: T;
              id?: T;
              blockName?: T;
            };
        regionCard?:
          | T
          | {
              image?: T;
              eyebrow?: T;
              title?: T;
              text?: T;
              ctaLabel?: T;
              ctaHref?: T;
              align?: T;
              id?: T;
              blockName?: T;
            };
        instagramStrip?:
          | T
          | {
              title?: T;
              handle?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        splitContent?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              text?: T;
              note?: T;
              amenitiesScope?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              reverse?: T;
              background?: T;
              ctaLabel?: T;
              gallery?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        differentials?:
          | T
          | {
              title?: T;
              cardsLimit?: T;
              perksLimit?: T;
              id?: T;
              blockName?: T;
            };
        suitesCarousel?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              text?: T;
              linkLabel?: T;
              linkHref?: T;
              showPrice?: T;
              id?: T;
              blockName?: T;
            };
        roomList?:
          | T
          | {
              intro?:
                | T
                | {
                    title?: T;
                    text?: T;
                    ctaLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cityBand?:
          | T
          | {
              title?: T;
              ghost?: T;
              text?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        offers?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              text?: T;
              limit?: T;
              linkLabel?: T;
              id?: T;
              blockName?: T;
            };
        social?:
          | T
          | {
              lead?: T;
              title?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              category?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              title?: T;
              showFilters?: T;
              allLabel?: T;
              id?: T;
              blockName?: T;
            };
        location?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              text?: T;
              poiTitle?: T;
              poiLimit?: T;
              showContactCards?: T;
              showMap?: T;
              id?: T;
              blockName?: T;
            };
        postList?:
          | T
          | {
              title?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        emptyState?:
          | T
          | {
              title?: T;
              text?: T;
              ctaLabel?: T;
              ctaHref?: T;
              onlyWhenEmpty?: T;
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              text?: T;
              form?: T;
              consentText?: T;
              asideTitle?: T;
              id?: T;
              blockName?: T;
            };
        confirmation?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              ctaLabel?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
      };
  showBookingBar?: T;
  showTestimonials?: T;
  testimonialsAfterBlock?: T;
  showNewsletter?: T;
  newsletterVariant?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suites_select".
 */
export interface SuitesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortName?: T;
  order?: T;
  summary?: T;
  description?: T;
  photos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  amenities?: T;
  maxGuests?: T;
  engineCode?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities_select".
 */
export interface AmenitiesSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  scope?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "differentials_select".
 */
export interface DifferentialsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  order?: T;
  image?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  description?: T;
  highlight?: T;
  minimumNights?: T;
  suites?: T;
  startsAt?: T;
  endsAt?: T;
  conditions?: T;
  validityRules?: T;
  whatsappLabel?: T;
  emailLabel?: T;
  engineLabel?: T;
  relatedOffers?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popups_select".
 */
export interface PopupsSelect<T extends boolean = true> {
  title?: T;
  isActive?: T;
  variant?: T;
  eyebrow?: T;
  heading?: T;
  text?: T;
  image?: T;
  imagePosition?: T;
  form?: T;
  consentText?: T;
  ctaLabel?: T;
  ctaType?: T;
  ctaHref?: T;
  ctaCheckIn?: T;
  ctaCheckOut?: T;
  trigger?: T;
  delaySeconds?: T;
  scrollPercent?: T;
  frequency?: T;
  frequencyDays?: T;
  hideAfterConvert?: T;
  startsAt?: T;
  endsAt?: T;
  showOn?: T;
  pages?: T;
  position?: T;
  size?: T;
  theme?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  title?: T;
  quote?: T;
  author?: T;
  source?: T;
  rating?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attractions_select".
 */
export interface AttractionsSelect<T extends boolean = true> {
  title?: T;
  distanceMeters?: T;
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-categories_select".
 */
export interface PhotoCategoriesSelect<T extends boolean = true> {
  title?: T;
  order?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  category?: T;
  lead?: T;
  excerpt?: T;
  image?: T;
  content?: T;
  relatedSuites?: T;
  relatedAttractions?: T;
  relatedPosts?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories_select".
 */
export interface PostCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-system_select".
 */
export interface DesignSystemSelect<T extends boolean = true> {
  name?: T;
  isActive?: T;
  colors?:
    | T
    | {
        brand?: T;
        brandDark?: T;
        ink?: T;
        inkSoft?: T;
        inkMute?: T;
        surface?: T;
        line?: T;
        footer?: T;
        dark?: T;
        accent?: T;
        whatsapp?: T;
      };
  typography?:
    | T
    | {
        displayFamily?: T;
        bodyFamily?: T;
        webfontUrl?: T;
        baseSize?: T;
        baseLineHeight?: T;
        headingSize?: T;
      };
  layout?:
    | T
    | {
        container?: T;
        sectionSpacing?: T;
        heroHeight?: T;
        pageHeroHeight?: T;
      };
  shape?:
    | T
    | {
        buttonRadius?: T;
        cardRadius?: T;
        cardShadow?: T;
      };
  promotion?:
    | T
    | {
        galleryHeight?: T;
        galleryGap?: T;
        contentGap?: T;
        relatedColumns?: T;
        detailMaxWidth?: T;
      };
  customCss?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  category?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  ghl?:
    | T
    | {
        enabled?: T;
        locationId?: T;
        source?: T;
        tags?:
          | T
          | {
              tag?: T;
              id?: T;
            };
        fieldMap?:
          | T
          | {
              formField?: T;
              target?: T;
              customKey?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  ghlStatus?: T;
  ghlContactId?: T;
  ghlError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  nav?:
    | {
        label: string;
        href: string;
        /**
         * Abrem num menu suspenso sob este item. O item de cima continua sendo um link.
         */
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  promoLabel?: string | null;
  promoHref?: string | null;
  bookLabel?: string | null;
  /**
   * Desmarcado, rola até a barra de reserva da página.
   */
  bookUsesEngine?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Duas ou três linhas sobre o hotel. Aparece na primeira coluna do rodapé.
   */
  about?: string | null;
  contactTitle?: string | null;
  phoneCaption?: string | null;
  reservationsCaption?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Aparecem discretos acima da linha final. Use PNG com fundo transparente; a altura é padronizada em 34px.
   */
  seals?:
    | {
        image: number | Media;
        /**
         * Lida por leitor de tela.
         */
        label: string;
        /**
         * Opcional.
         */
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  bottomText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-bar".
 */
export interface BookingBar {
  id: number;
  engineBaseUrl: string;
  hotelChain: string;
  hotelId: string;
  currencyId: string;
  language: string;
  checkInLabel?: string | null;
  checkOutLabel?: string | null;
  guestsLabel?: string | null;
  submitLabel?: string | null;
  maxGuests: number;
  defaultGuests: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-section".
 */
export interface NewsletterSection {
  id: number;
  background?: (number | null) | Media;
  homeTitle?: string | null;
  homeSubtitle?: string | null;
  innerTitle?: string | null;
  innerSubtitle?: string | null;
  namePlaceholder?: string | null;
  emailPlaceholder?: string | null;
  phonePlaceholder?: string | null;
  submitLabel?: string | null;
  consentText?: string | null;
  /**
   * Criado em Formulários. Sem ele o cadastro não é gravado em lugar nenhum.
   */
  form?: (number | null) | Form;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials-section".
 */
export interface TestimonialsSection {
  id: number;
  /**
   * Vazio esconde a linha. Ex.: "Avaliações".
   */
  eyebrow?: string | null;
  /**
   * A última palavra sai em vermelho automaticamente, como no layout.
   */
  title?: string | null;
  /**
   * Parágrafo abaixo do título. Vazio esconde.
   */
  lead?: string | null;
  /**
   * Vazio esconde o botão.
   */
  ctaLabel?: string | null;
  ctaHref?: string | null;
  source: 'auto' | 'manual';
  limit?: number | null;
  items?: (number | Testimonial)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "floating-actions".
 */
export interface FloatingAction {
  id: number;
  showWhatsapp?: boolean | null;
  showActionBar?: boolean | null;
  /**
   * O último item sai destacado em vermelho.
   */
  actionBar?:
    | {
        label: string;
        action: 'phone' | 'reservations' | 'whatsapp' | 'engine' | 'link';
        href?: string | null;
        /**
         * Opcional. Vazio, usa o ícone da ação.
         */
        icon?:
          | (
              | 'i-coffee'
              | 'i-wifi'
              | 'i-parking'
              | 'i-paw'
              | 'i-card'
              | 'i-wa'
              | 'i-bed'
              | 'i-ac'
              | 'i-tv'
              | 'i-desk'
              | 'i-dryer'
              | 'i-bath'
              | 'i-minibar'
              | 'i-phone'
              | 'i-mail'
              | 'i-pin'
              | 'i-star'
              | 'i-tag'
              | 'i-promo'
              | 'i-cal'
              | 'i-pool'
              | 'i-ev'
              | 'i-clean'
              | 'i-fan'
              | 'i-ig'
              | 'i-fb'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  showCookie?: boolean | null;
  cookieText?: string | null;
  cookieMoreLabel?: string | null;
  cookieMoreHref?: string | null;
  cookieAcceptLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotion-page".
 */
export interface PromotionPage {
  id: number;
  regulationTitle?: string | null;
  relatedTitle?: string | null;
  conditionsLabel?: string | null;
  validityLabel?: string | null;
  /**
   * Use {n} no lugar da quantidade.
   */
  minimumNightsTemplate?: string | null;
  showWhatsapp?: boolean | null;
  showEmail?: boolean | null;
  showEngine?: boolean | null;
  whatsappLabel?: string | null;
  emailLabel?: string | null;
  engineLabel?: string | null;
  /**
   * Use {title} para inserir o nome da promoção.
   */
  whatsappMessage?: string | null;
  /**
   * Use {title} para inserir o nome da promoção.
   */
  emailSubject?: string | null;
  showTestimonials?: boolean | null;
  showNewsletter?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  hotelName: string;
  tagline?: string | null;
  /**
   * PNG com fundo transparente.
   */
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  phoneLabel?: string | null;
  /**
   * Vira o link tel:
   */
  phoneE164?: string | null;
  reservationsLabel?: string | null;
  reservationsE164?: string | null;
  /**
   * Monta https://wa.me/…
   */
  whatsapp?: string | null;
  email?: string | null;
  address?: string | null;
  socials?:
    | {
        network: 'instagram' | 'facebook';
        handle: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  latitude?: number | null;
  longitude?: number | null;
  mapZoom?: number | null;
  /**
   * Trocar aqui muda o estilo do mapa. Atenção ao provedor: o CARTO, que era o padrão, passou a exigir chave e devolve tiles escritos "API KEY REQUIRED" — o mapa carrega e parece quebrado.
   */
  tileUrl?: string | null;
  tileAttribution?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  promoLabel?: T;
  promoHref?: T;
  bookLabel?: T;
  bookUsesEngine?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  about?: T;
  contactTitle?: T;
  phoneCaption?: T;
  reservationsCaption?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  seals?:
    | T
    | {
        image?: T;
        label?: T;
        href?: T;
        id?: T;
      };
  bottomText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-bar_select".
 */
export interface BookingBarSelect<T extends boolean = true> {
  engineBaseUrl?: T;
  hotelChain?: T;
  hotelId?: T;
  currencyId?: T;
  language?: T;
  checkInLabel?: T;
  checkOutLabel?: T;
  guestsLabel?: T;
  submitLabel?: T;
  maxGuests?: T;
  defaultGuests?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-section_select".
 */
export interface NewsletterSectionSelect<T extends boolean = true> {
  background?: T;
  homeTitle?: T;
  homeSubtitle?: T;
  innerTitle?: T;
  innerSubtitle?: T;
  namePlaceholder?: T;
  emailPlaceholder?: T;
  phonePlaceholder?: T;
  submitLabel?: T;
  consentText?: T;
  form?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials-section_select".
 */
export interface TestimonialsSectionSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lead?: T;
  ctaLabel?: T;
  ctaHref?: T;
  source?: T;
  limit?: T;
  items?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "floating-actions_select".
 */
export interface FloatingActionsSelect<T extends boolean = true> {
  showWhatsapp?: T;
  showActionBar?: T;
  actionBar?:
    | T
    | {
        label?: T;
        action?: T;
        href?: T;
        icon?: T;
        id?: T;
      };
  showCookie?: T;
  cookieText?: T;
  cookieMoreLabel?: T;
  cookieMoreHref?: T;
  cookieAcceptLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotion-page_select".
 */
export interface PromotionPageSelect<T extends boolean = true> {
  regulationTitle?: T;
  relatedTitle?: T;
  conditionsLabel?: T;
  validityLabel?: T;
  minimumNightsTemplate?: T;
  showWhatsapp?: T;
  showEmail?: T;
  showEngine?: T;
  whatsappLabel?: T;
  emailLabel?: T;
  engineLabel?: T;
  whatsappMessage?: T;
  emailSubject?: T;
  showTestimonials?: T;
  showNewsletter?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  hotelName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  phoneLabel?: T;
  phoneE164?: T;
  reservationsLabel?: T;
  reservationsE164?: T;
  whatsapp?: T;
  email?: T;
  address?: T;
  socials?:
    | T
    | {
        network?: T;
        handle?: T;
        url?: T;
        id?: T;
      };
  latitude?: T;
  longitude?: T;
  mapZoom?: T;
  tileUrl?: T;
  tileAttribution?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}